serverPort               : 8082
BTCNodeIsTestnet         : true
BTCNodeHost              : 172.17.0.1
BTCNodePort              : 18332
BTCNodeUser              : bitcoinrpcuser
BTCNodePassword          : bitcoinrpcpassword
ERGONodeHost             : 172.17.0.1
ERGONodePort             : 9052
blockchainScanDelay      : 1000000
dbPath                   : "/db-2"
ownPeerAddress           : "http://ergvein-index-server-2:8082"
knownPeers               :
                           - "http://ergvein-index-server-1:8081"
peerActualizationDelay   : 10000000
peerActualizationTimeout : 86400