language: nix
nix: 2.3
env:
  global:
  - secure: "SW7XDQlFaHJDrY29VaFwCIW+QBtjY4/kKDS/vFGQq6BGxFuIqkv0nPZ36ONI76/cDZ+tyacijkWhTGL/zftnqHAgkbuK5zgD1KMedypbUL/RvW2tWKkhkUZ9cp7NUYY/60QfCv93ySgMM+nU1WqwbV/JgWjoFqzedN/su/g76Bm429V4FHK+rLGhGLbta4gHCRLe1GG4WDFOeaBrzTWd5wCz247SD9VEF97Cj8HVoqtFYTuLBvWee6JWE8l/IzG4iAlf12enCZUbk7CkDHYt9vemF+2Z1IWSlA9Rr70s+u7ZzHklgBvFHVyzt7wXVUrqhSWgX3bbd6UNR0Q9ThocWcvmD38PzcW3XyyDswuuhMlf84/qN8wJXGHc1E7grt1xJ1cz6mC7jbWYH3VvU0jhkR7lMJ+oV5hES2IAD8G+YnYozcCb4tiqgg3sizGkFfJ0DRUinK8L9NwzWf6bG33yKomgq3LhCekl2o1OlPkmzqGQlm8o11f8ClyHQaasreYmM0tx5wmbZTdl2F2ZPrh+LIy88TAYQirU25ZZSwkUwU8Sg6e/AKsaIaFlbzh67sIICKEImjdFbKhv8GmCAzzf/9iTADk7TBp1A6jXs1pbYLM4P+u8N1/sYwDQR/3L9dfCACiVxhWDvQ2doIYR/se3UtjQvhg2YvuIw2H9ZmnX+II="
before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ https://nixcache.reflex-frp.org" | sudo tee
  -a /etc/nix/nix.conf > /dev/null
- echo "trusted-public-keys = ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" | sudo tee
  -a /etc/nix/nix.conf > /dev/null
before_script:
- nix-env -iA cachix -f https://cachix.org/api/v1/install
- cachix use ergvein
- cachix push ergvein --watch-store&

script:
- echo "travis_fold:start:Desktop"
- nix-build -A ghc.ergvein-wallet
- echo "travis_fold:end:Desktop"

- echo "travis_fold:start:IndexServer"
- nix-build -A ghc.ergvein-index-server
- echo "travis_fold:end:IndexServer"

- echo "travis_fold:start:Android"
- nix-build --arg isAndroid true -A android.ergvein-wallet
- echo "travis_fold:end:Android"