serverPort           : 8080
dbHost               : localhost
dbPort               : 5434
dbUser               : localDb
dbPassword           : ""
dbName               : localDb
cachePath            : "/ergveinCache"
BTCNodeIsTestnet     : true
BTCNodeHost          : localhost
BTCNodePort          : 18332
BTCNodeUser          : bitcoinrpc
BTCNodePassword      : password
ERGONodeHost         : localhost
ERGONodePort         : 9052
blockchainScanDelay  : 1000000
dbLog                : true
pubScriptHistoryScan : false