serverPort : 8080
dbHost     : localhost
dbPort     : 5434
dbUser     : localDb
dbPassword : ""
dbName     : localDb
BTCNodeHost     : localhost
BTCNodePort     : 18332
BTCNodeUser     : bitcoinrpc
BTCNodePassword : password