name: Main
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-desktop:
    name: Build desktop platform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install Nix
      uses: cachix/install-nix-action@v8

    - name: Setup cachix
      uses: cachix/cachix-action@v6
      with:
        name: ergvein
        signingKey: ${{ secrets.CACHIX_KEY }}
    
    - name: Build indexer server
      run: nix-build -A ghc.ergvein-index-server
    
    - name: Build desktop wallet
      run: nix-build -A ghc.ergvein-wallet

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
      
    - name: Build and upload docker images 
      run: cd nix && ./ci-build-docker.sh
      env:
        DOCKER_USERNAME: ergvein
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        GITHUB_BRANCH: ${{ steps.extract_branch.outputs.branch }}

  build-android:
    name: Build android platform
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Remove Nix 	
      run: |	
        sudo systemctl stop nix-daemon.socket	|| true
        sudo systemctl stop nix-daemon.service	|| true
        sudo systemctl disable nix-daemon.socket	|| true
        sudo systemctl disable nix-daemon.service	|| true
        sudo systemctl daemon-reload	|| true
        sudo mv /etc/profile.d/nix.sh.backup-before-nix /etc/profile.d/nix.sh	|| true
        sudo rm -rf /etc/nix/nix.conf || true
        sudo rm -rf /etc/nix /nix /root/.nix-profile /root/.nix-defexpr /root/.nix-channels /home/actions/.nix-profile /home/actions/.nix-defexpr /home/actions/.nix-channels || true
    
    - name: Install Nix	
      uses: cachix/install-nix-action@v9	
      with:	
        nix_path: nixpkgs=channel:nixos-unstable	

    - name: Reload shell 	
      run: |	
        source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh 
        source /nix/var/nix/profiles/default/etc/profile.d/nix.sh
        echo "::add-path::/nix/var/nix/profiles/per-user/actions/profile/bin"
        echo "trusted-users = root $USER\nmax-jobs = 4" | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon
    - name: set environment variables
      uses: allenevans/set-env@v1.0.0
      with:
        MY_ENV_VAR: 'my value'
          
    - name: Setup cachix
      uses: cachix/cachix-action@v6
      with:
        name: ergvein
        signingKey: ${{ secrets.CACHIX_KEY }}

    - name: Build android wallet 
      run: |  
        nix-build -A android.ergvein-wallet
