name: Main
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-desktop:
    name: Build desktop platform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install Nix
      uses: cachix/install-nix-action@v8

    - name: Setup cachix
      uses: cachix/cachix-action@v6
      with:
        name: ergvein
        signingKey: ${{ secrets.CACHIX_KEY }}
    
    - name: Build indexer server
      run: nix-build -A ghc.ergvein-index-server
    
    - name: Build desktop wallet
      run: nix-build -A ghc.ergvein-wallet

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
      
    - name: Build and upload docker images 
      run: cd nix && ./ci-build-docker.sh
      env:
        DOCKER_USERNAME: ergvein
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        GITHUB_BRANCH: ${{ steps.extract_branch.outputs.branch }}

  build-android:
    name: Build android platform
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install Nix
      uses: cachix/install-nix-action@v8

    - name: Setup cachix
      uses: cachix/cachix-action@v6
      with:
        name: ergvein
        signingKey: ${{ secrets.CACHIX_KEY }}
    
    - name: Cleanup disk space 
      run: |
        df -h
        sudo apt-get clean
        nix-collect-garbage -d
        df -h

    - name: Build android wallet 
      run: | 
        nix-build -A android.ergvein-wallet
