name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install Nix
      uses: cachix/install-nix-action@v8

    - name: Setup cachix
      uses: cachix/cachix-action@v6
      with:
        name: ergvein
        signingKey: ${{ secrets.CACHIX_KEY }}
    
    - name: Build indexer server
      run: nix-build -A ghc.ergvein-index-server
    
    - name: Build desktop wallet
      run: nix-build -A ghc.ergvein-wallet
    
    - name: Build android wallet 
      run: nix-build -A android.ergvein-wallet

    - name: Build and upload docker images 
      run: cd nix && ./ci-build-docker.sh
      env:
        DOCKER_USERNAME: ergvein
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
