name: Publish

on:
  push:
    tags:
    - 'v*'

jobs:
  docker:
    name: Build and publish docker containers
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09

    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: ergvein
        signingKey: ${{ secrets.CACHIX_KEY }}

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed -r 's/\/+/-/g')"
      id: extract_branch

    - name: Build and upload docker images
      run: cd nix && ./ci-build-docker.sh
      env:
        DOCKER_USERNAME: ergvein
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        GITHUB_BRANCH: ${{ steps.extract_branch.outputs.branch }}

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_USERNAME: ergvein
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: ergvein/ergvein-index-server

  desktop:
    name: Build and cache desktop package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09

    - name: Setup cachix
      uses: cachix/cachix-action@v8
      with:
        name: ergvein
        signingKey: ${{ secrets.CACHIX_KEY }}

    - name: Build indexer server
      run: nix-build -A ghc.ergvein-index-server

    - name: Build desktop wallet
      run: nix-build -A ghc.ergvein-wallet

  android:
    name: Build and publish android release
    runs-on: self-hosted
    steps:

    - name: Restore permissions on repo
      run: sudo chown -R actions /home/actions/_work/ergvein/ergvein

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Remove Nix
      run: |
        sudo systemctl stop nix-daemon.socket	|| true
        sudo systemctl stop nix-daemon.service	|| true
        sudo systemctl disable nix-daemon.socket	|| true
        sudo systemctl disable nix-daemon.service	|| true
        sudo systemctl daemon-reload	|| true
        sudo mv /etc/profile.d/nix.sh.backup-before-nix /etc/profile.d/nix.sh	|| true
        sudo rm -rf /etc/nix/nix.conf || true
        sudo rm -rf /etc/nix /nix /root/.nix-profile /root/.nix-defexpr /root/.nix-channels /home/actions/.nix-profile /home/actions/.nix-defexpr /home/actions/.nix-channels || true

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09

    - name: Reload shell
      run: |
        source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
        source /nix/var/nix/profiles/default/etc/profile.d/nix.sh
        echo "/nix/var/nix/profiles/per-user/actions/profile/bin" >> $GITHUB_PATH
        echo "trusted-users = root $USER" | sudo tee -a /etc/nix/nix.conf
        echo "sandbox = false" | sudo tee -a /etc/nix/nix.conf
        sudo pkill nix-daemon
        for n in $(seq 1 20)
        do
          if getent passwd nixbld$n > /dev/null 2>&1
          then
              echo "User nixbld$n is already created"
          else
              sudo useradd -c "Nix build user $n" -d /var/empty -g nixbld -G nixbld -M -N -r -s "$(which nologin)" nixbld$n
          fi
        done

    - name: Setup cachix
      uses: cachix/cachix-action@v8
      with:
        name: ergvein
        signingKey: ${{ secrets.CACHIX_KEY }}

    - name: Git-Crypt Unlock
      uses: zemuldo/git-crypt-unlock@v2.0
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
        GPG_KEY_PASS: ${{ secrets.GPG_KEY_PASS }}

    - name: Build android wallet
      run: |
        source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
        source /nix/var/nix/profiles/default/etc/profile.d/nix.sh
        nix-channel --add https://nixos.org/channels/nixos-20.09 nixpkgs
        nix-channel --update
        ./release-android.sh

    - name: Git-Crypt Lock
      run: sudo git-crypt lock

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release APK
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: android-release-apk/release/android-app-release.apk
        asset_name: ergvein.apk
        asset_content_type: application/zip

    - name: Upload Android Release to Play Store
      uses: r0adkll/upload-google-play@3ea191f69b364a922c2af186abe5a12cc40922ce
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_ERGVEIN_SECRET }}
        packageName: org.ergvein.wallet
        releaseFiles: android-release/release/android-app.aab
        track: "Internal Alpha"
        whatsNewDirectory: whatsnew
